"""change nullable option on owner in links

Revision ID: d623869eb95b
Revises: 8311067c622d
Create Date: 2025-03-20 19:28:51.282492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd623869eb95b'
down_revision: Union[str, None] = '8311067c622d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'owner',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('links', 'owner',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
